feat(ci): add gcp deploy action
konstellation-io/ny-house-price-estimator pull request #10
Opened 2022-03-15 10:27 UTC by JYisus

Add GCP deploy workflow migrated from Gitlab CI [https://gitlab.intelygenz.com/konstellation-io/kre-demo](https://gitlab.intelygenz.com/konstellation-io/kre-demo).

2022-03-15 13:18 UTC, alpiquero requested changes
Some changes requested.

2022-03-15 13:18 UTC, alpiquero commented on .github/workflows/app_deploy-gcp.yaml
> +        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
If the image tags are being generated without the `v` prefix (Ex: `1.0.0` and not `v1.0.0`), should't this line must be like follows?
```
run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/demo-v}
```

2022-03-15 13:18 UTC, alpiquero commented on app/deploy/ingress.yaml
> +#    nginx.ingress.kubernetes.io/whitelist-source-range: "46.27.217.76/32"
Remove this comment as it could contain sensitive info.

2022-03-17 07:32 UTC, aacecandev commented
Is it needed to keep the .vscode folder in the repo?

2022-03-17 09:22 UTC, aacecandev requested changes

2022-03-21 09:25 UTC, aacecandev approved these changes

2022-03-21 09:34 UTC, merged

2022-03-21 09:41 UTC, alejandrogr commented
:tada: This PR is included in version demo-v1.1.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/ny-house-price-estimator/releases/tag/demo-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-21 09:55 UTC, alejandrogr commented
:tada: This PR is included in version demo-v1.1.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/ny-house-price-estimator/releases/tag/demo-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-22 10:17 UTC, alejandrogr commented
:tada: This PR is included in version demo-v1.1.0 :tada:

The release is available on [GitHub release](https://github.com/konstellation-io/ny-house-price-estimator/releases/tag/demo-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-10-03 11:57 UTC, alejandrogr commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `v1.0.0`
- [GitHub release](https://github.com/konstellation-io/ny-house-price-estimator/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: